name: event_manager_objectbox
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  objectbox: ^1.6.2
  objectbox_sync_flutter_libs: any
  cupertino_icons: ^1.0.2
  intl: any
  flat_buffers: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  objectbox_generator: any
 
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true