name: objectbox_generator_test

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  objectbox:
  json_serializable:
  json_annotation: "^4.3.0"
  freezed_annotation:

dev_dependencies:
  freezed:
  objectbox_generator:
  test:
  build_runner:
  build_test:
  io:
  path:

dependency_overrides:
  # Temporary: freezed 2.0.4+ requires 4.2.0, but doesn't declare so.
  # https://github.com/rrousselGit/freezed/issues/700
  analyzer: ">=4.2.0 <5.0.0"
  objectbox:
    path: ../../../objectbox
  objectbox_generator:
    path: ../../